# Generated by Django 5.2.8 on 2025-11-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='major_category',
            field=models.CharField(blank=True, choices=[('new_arrivals', 'New Arrivals'), ('featured', 'Featured'), ('best_selling', 'Best Selling'), ('none', 'None')], default='new_arrivals', max_length=20),
        ),
    ]
