# Generated by Django 5.2.8 on 2025-11-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_sku_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_sku_8a55cb_idx',
            old_name='store_produ_sku_idx',
        ),
    ]
