# Generated by Django 5.2.8 on 2025-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_store_produ_sku_idx_store_produ_sku_8a55cb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code generated for this lead', max_length=50, null=True),
        ),
    ]
