# Generated by Django 5.2.8 on 2025-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_lead_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Banner text to display at the top of the site', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Show this banner if active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Banner expiry date/time (optional)', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
