# Generated by Django 5.2.8 on 2025-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='show_on_banner',
            field=models.BooleanField(default=False, help_text='Show this coupon in the top offer banner'),
        ),
    ]
