# Generated by Django 5.2.8 on 2025-11-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerprofile_allowed_major_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_phone',
            field=models.CharField(max_length=30),
        ),
    ]
