# Generated by Django 5.2.8 on 2025-12-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
