# Generated by Django 5.2.8 on 2025-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Human-readable order number', max_length=20, null=True, unique=True),
        ),
    ]
