# Generated by Django 5.2.8 on 2025-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment gateway order/transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cashfree', 'Cashfree'), ('cod', 'Cash on Delivery')], default='cod', help_text='Payment method used for this order', max_length=20),
        ),
    ]
