# Generated by Django 5.2.8 on 2025-12-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=75.0, help_text='Delivery charge for the order', max_digits=7),
        ),
    ]
